export const cardPlanItems = [
  {
    imageUrl: 'static/images/cardPlansImages/free.svg',
    title: 'free',
    text: 'Teste grátis agora mesmo',
    textMobile:
      'Faça um teste gratuito e descubra como podemos transformar digitalmente a sua empresa.',
    subText: '',
    buttonText: '14 dias grátis',
    buttonColor: 'green',
    url: '/free-trial',
  },
  {
    imageUrl: 'static/images/cardPlansImages/startup.svg',
    title: 'startup',
    text: 'Para pequenas empresas ou startups que precisam de poucas integrações.',
    subText: 'Sob consulta',
    buttonText: 'Fale conosco',
    buttonColor: 'secondary',
    url: '/fale-com-um-especialista',
  },
  {
    imageUrl: 'static/images/cardPlansImages/devapi.svg',
    title: 'devapi',
    text: 'Para empresas que precisam construir seus próprios projetos de integrações.',
    subText: 'Sob consulta',
    buttonText: 'Fale conosco',
    buttonColor: 'secondary',
    url: '/fale-com-um-especialista',
  },
  {
    imageUrl: 'static/images/cardPlansImages/business.svg',
    title: 'business',
    text: 'Para empresa que precisam de integrações e conectores customizáveis.',
    subText: 'Sob consulta',
    buttonText: 'Fale conosco',
    buttonColor: 'secondary',
    url: '/fale-com-um-especialista',
  },
  {
    imageUrl: 'static/images/cardPlansImages/enterprise.svg',
    title: 'enterprise',
    text: 'Para grandes empresas que tenham necessidade de diversas integrações complexas.',
    subText: 'Sob consulta',
    buttonText: 'Fale conosco',
    buttonColor: 'secondary',
    url: '/fale-com-um-especialista',
  },
]
