export const departaments = [
  'Software e Cloud',
  'Agronegócio',
  'Consultorias e Treinamentos',
  'E-commerce',
  'Educação e Ensino',
  'Engenharia e Indústria Geral',
  'Eventos',
  'Financeiro / Jurídico',
  'Governo e Órgãos Públicos',
  'Hardware e Eletrônicos',
  'Mídia e Comunicação',
  'ONGs',
  'Saúde e Estética',
  'Serviços em Geral',
  'Serviços em RH e Coaching',
  'Agência de Marketing e Publicidade',
  'Telecomunicações',
  'Turismo e Lazer',
  'Varejo',
  'Logística',
  'Outros',
]
